// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CancelOrderData, CancelOrderErrors, CancelOrderResponses, GetBalancesData, GetBalancesErrors, GetBalancesResponses, GetChartsData, GetChartsErrors, GetChartsResponses, GetConversionRatesBatchData, GetConversionRatesBatchErrors, GetConversionRatesBatchResponses, GetConversionRateSingleData, GetConversionRateSingleErrors, GetConversionRateSingleResponses, GetDepthData, GetDepthErrors, GetDepthResponses, GetHistoryOrderData, GetHistoryOrderErrors, GetHistoryOrderResponses, GetLimitsData, GetLimitsErrors, GetLimitsResponses, GetNowData, GetNowErrors, GetNowResponses, GetOrderData, GetOrderErrors, GetOrderResponses, GetOrdersData, GetOrdersErrors, GetOrdersHistoryData, GetOrdersHistoryErrors, GetOrdersHistoryResponses, GetOrdersResponses, GetPositionsData, GetPositionsErrors, GetPositionsResponses, GetStateData, GetStateErrors, GetStateResponses, GetSymbolData, GetSymbolErrors, GetSymbolResponses, GetSymbolsData, GetSymbolsErrors, GetSymbolsResponses, GetTobData, GetTobErrors, GetTobResponses, GetTradesData, GetTradesErrors, GetTradesResponses, GetTransfersHistoryData, GetTransfersHistoryErrors, GetTransfersHistoryResponses, LogoutData, LogoutErrors, LogoutResponses, ModifyOrderData, ModifyOrderErrors, ModifyOrderResponses, ModifyOrderSltpData, ModifyOrderSltpErrors, ModifyOrderSltpResponses, ModifyPositionSltpData, ModifyPositionSltpErrors, ModifyPositionSltpResponses, PlaceOrderData, PlaceOrderErrors, PlaceOrderResponses, PostAuthorizeData, PostAuthorizeErrors, PostAuthorizeResponses, PostPasswordData, PostPasswordErrors, PostPasswordResponses, PostRefreshData, PostRefreshErrors, PostRefreshResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * User authentication
 *
 * Username and password authentication.
 *
 * `Weight` 5.
 *
 */
export const postAuthorize = <ThrowOnError extends boolean = false>(options: Options<PostAuthorizeData, ThrowOnError>) => (options.client ?? client).post<PostAuthorizeResponses, PostAuthorizeErrors, ThrowOnError>({
    responseType: 'json',
    url: '/authorize',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Refresh API token
 *
 * Refresh API token.
 *
 * `Weight` 5.
 *
 */
export const postRefresh = <ThrowOnError extends boolean = false>(options: Options<PostRefreshData, ThrowOnError>) => (options.client ?? client).post<PostRefreshResponses, PostRefreshErrors, ThrowOnError>({
    responseType: 'json',
    url: '/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Logout
 *
 * Send logout.
 *
 * `Weight` 2.
 *
 */
export const logout = <ThrowOnError extends boolean = false>(options: Options<LogoutData, ThrowOnError>) => (options.client ?? client).post<LogoutResponses, LogoutErrors, ThrowOnError>({
    responseType: 'json',
    url: '/logout',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Change password
 *
 * Change trading account password.
 *
 * `Weight` 5.
 *
 */
export const postPassword = <ThrowOnError extends boolean = false>(options: Options<PostPasswordData, ThrowOnError>) => (options.client ?? client).post<PostPasswordResponses, PostPasswordErrors, ThrowOnError>({
    responseType: 'json',
    url: '/password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Rate limits
 *
 * Get rate limits and unfilled order count limits.
 *
 * `Weight` 5.
 *
 */
export const getLimits = <ThrowOnError extends boolean = false>(options: Options<GetLimitsData, ThrowOnError>) => (options.client ?? client).get<GetLimitsResponses, GetLimitsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/limits',
    ...options
});

/**
 * Get symbol
 *
 * Returns configuration for symbol.
 *
 * `Weight` 2.
 *
 */
export const getSymbol = <ThrowOnError extends boolean = false>(options: Options<GetSymbolData, ThrowOnError>) => (options.client ?? client).get<GetSymbolResponses, GetSymbolErrors, ThrowOnError>({
    responseType: 'json',
    url: '/symbols/get/{symbolName}',
    ...options
});

/**
 * Get all symbols
 *
 * Returns configuration for all available symbols.
 *
 * `Weight` 20.
 *
 */
export const getSymbols = <ThrowOnError extends boolean = false>(options: Options<GetSymbolsData, ThrowOnError>) => (options.client ?? client).get<GetSymbolsResponses, GetSymbolsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/symbols/query',
    ...options
});

/**
 * Trading account state
 *
 * Get trading account information.
 *
 * Consider using WebSocket API instead, as it can decrease the workload on the servers.
 *
 * `Weight` 20.
 *
 */
export const getState = <ThrowOnError extends boolean = false>(options: Options<GetStateData, ThrowOnError>) => (options.client ?? client).post<GetStateResponses, GetStateErrors, ThrowOnError>({
    responseType: 'json',
    url: '/account/state',
    ...options
});

/**
 * Balances/collaterial for an account
 *
 * Get balances/collaterial for an account.
 *
 * `Weight` 20.
 *
 */
export const getBalances = <ThrowOnError extends boolean = false>(options: Options<GetBalancesData, ThrowOnError>) => (options.client ?? client).get<GetBalancesResponses, GetBalancesErrors, ThrowOnError>({
    responseType: 'json',
    url: '/account/balances',
    ...options
});

/**
 * Open orders
 *
 * Get working and inactive orders.
 *
 * Consider using WebSocket API instead, as it can decrease the workload on the servers.
 *
 * `Weight` 20.
 *
 */
export const getOrders = <ThrowOnError extends boolean = false>(options: Options<GetOrdersData, ThrowOnError>) => (options.client ?? client).post<GetOrdersResponses, GetOrdersErrors, ThrowOnError>({
    responseType: 'json',
    url: '/orders/open',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get single open order by order id
 *
 * Get working or inactive order.
 *
 * Consider using WebSocket API instead, as it can decrease the workload on the servers.
 *
 * `Weight` 4.
 *
 */
export const getOrder = <ThrowOnError extends boolean = false>(options: Options<GetOrderData, ThrowOnError>) => (options.client ?? client).post<GetOrderResponses, GetOrderErrors, ThrowOnError>({
    responseType: 'json',
    url: '/orders/open/single',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Orders history
 *
 * Get order history for an account. Returned orders will have a final status (`Rejected`,
 * `Filled`, `Cancelled` and `Expired`).
 *
 * `Weight` 20.
 *
 */
export const getOrdersHistory = <ThrowOnError extends boolean = false>(options: Options<GetOrdersHistoryData, ThrowOnError>) => (options.client ?? client).post<GetOrdersHistoryResponses, GetOrdersHistoryErrors, ThrowOnError>({
    responseType: 'json',
    url: '/orders/completed',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get single historical order
 *
 * Returns single order in a final state (Rejected, Filled, Cancelled and Expired). Available history depths is limited due to performance reasons.
 *
 * `Weight` 20.
 *
 */
export const getHistoryOrder = <ThrowOnError extends boolean = false>(options: Options<GetHistoryOrderData, ThrowOnError>) => (options.client ?? client).post<GetHistoryOrderResponses, GetHistoryOrderErrors, ThrowOnError>({
    responseType: 'json',
    url: '/orders/completed/single',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Place order
 *
 * Place a new order.
 *
 * `Weight` 1.
 *
 */
export const placeOrder = <ThrowOnError extends boolean = false>(options: Options<PlaceOrderData, ThrowOnError>) => (options.client ?? client).post<PlaceOrderResponses, PlaceOrderErrors, ThrowOnError>({
    responseType: 'json',
    url: '/order',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Modify order
 *
 * Modify an existing order.
 *
 * `Weight` 1.
 *
 */
export const modifyOrder = <ThrowOnError extends boolean = false>(options: Options<ModifyOrderData, ThrowOnError>) => (options.client ?? client).put<ModifyOrderResponses, ModifyOrderErrors, ThrowOnError>({
    url: '/order',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Cancel order
 *
 * Cancel an existing order.
 *
 * `Weight` 1.
 *
 */
export const cancelOrder = <ThrowOnError extends boolean = false>(options: Options<CancelOrderData, ThrowOnError>) => (options.client ?? client).delete<CancelOrderResponses, CancelOrderErrors, ThrowOnError>({ url: '/order/{orderId}', ...options });

/**
 * Modify stop loss and/or take profit of order
 *
 * Modify stop loss and/or take profit of order.
 *
 * `Weight` 1.
 *
 */
export const modifyOrderSltp = <ThrowOnError extends boolean = false>(options: Options<ModifyOrderSltpData, ThrowOnError>) => (options.client ?? client).put<ModifyOrderSltpResponses, ModifyOrderSltpErrors, ThrowOnError>({
    responseType: 'json',
    url: '/order/sltp',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Modify stop loss and/or take profit of position
 *
 * Modify stop loss and/or take profit of position.
 *
 * `Weight` 1.
 *
 */
export const modifyPositionSltp = <ThrowOnError extends boolean = false>(options: Options<ModifyPositionSltpData, ThrowOnError>) => (options.client ?? client).put<ModifyPositionSltpResponses, ModifyPositionSltpErrors, ThrowOnError>({
    responseType: 'json',
    url: '/sltp',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Open positions
 *
 * Get positions for an account.
 *
 * Consider using WebSocket API instead, as it can decrease the workload on the servers.
 *
 * `Weight` 20.
 *
 */
export const getPositions = <ThrowOnError extends boolean = false>(options: Options<GetPositionsData, ThrowOnError>) => (options.client ?? client).post<GetPositionsResponses, GetPositionsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/positions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Trades history
 *
 * Get a list of trades.
 *
 * `Weight` 20.
 *
 */
export const getTrades = <ThrowOnError extends boolean = false>(options: Options<GetTradesData, ThrowOnError>) => (options.client ?? client).post<GetTradesResponses, GetTradesErrors, ThrowOnError>({
    responseType: 'json',
    url: '/trades',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Charts
 *
 * Request for history chart bars.
 *
 * `Weight` 5.
 *
 */
export const getCharts = <ThrowOnError extends boolean = false>(options: Options<GetChartsData, ThrowOnError>) => (options.client ?? client).post<GetChartsResponses, GetChartsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/charts',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Depth of the market
 *
 * Get current depth of market for the instrument.
 * `Weight` 25.
 *
 */
export const getDepth = <ThrowOnError extends boolean = false>(options: Options<GetDepthData, ThrowOnError>) => (options.client ?? client).get<GetDepthResponses, GetDepthErrors, ThrowOnError>({
    responseType: 'json',
    url: '/depth/{symbolName}',
    ...options
});

/**
 * Get top of the book
 *
 * Get the best bid and ask of the instrument.
 *
 * `Weight` 2.
 *
 */
export const getTob = <ThrowOnError extends boolean = false>(options: Options<GetTobData, ThrowOnError>) => (options.client ?? client).get<GetTobResponses, GetTobErrors, ThrowOnError>({
    responseType: 'json',
    url: '/quote/{symbolName}',
    ...options
});

/**
 * Cash/asset transfers history
 *
 * Get cash/asset transfers history for an account.
 *
 * `Weight` 20.
 *
 */
export const getTransfersHistory = <ThrowOnError extends boolean = false>(options: Options<GetTransfersHistoryData, ThrowOnError>) => (options.client ?? client).post<GetTransfersHistoryResponses, GetTransfersHistoryErrors, ThrowOnError>({
    responseType: 'json',
    url: '/transfers',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get single conversion rate
 *
 * Get conversion rate for a single currency pair.
 *
 * `Weight` 2.
 *
 */
export const getConversionRateSingle = <ThrowOnError extends boolean = false>(options: Options<GetConversionRateSingleData, ThrowOnError>) => (options.client ?? client).post<GetConversionRateSingleResponses, GetConversionRateSingleErrors, ThrowOnError>({
    responseType: 'json',
    url: '/conversion-rate/single',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get conversion rates (batch)
 *
 * Get conversion rates for multiple currency pairs.
 *
 * Maximum 100 items per request.
 *
 * `Weight` 5.
 *
 */
export const getConversionRatesBatch = <ThrowOnError extends boolean = false>(options: Options<GetConversionRatesBatchData, ThrowOnError>) => (options.client ?? client).post<GetConversionRatesBatchResponses, GetConversionRatesBatchErrors, ThrowOnError>({
    responseType: 'json',
    url: '/conversion-rate/batch',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Health check
 *
 * Returns current time and server version.
 *
 * `Weight` 1.
 *
 */
export const getNow = <ThrowOnError extends boolean = false>(options?: Options<GetNowData, ThrowOnError>) => (options?.client ?? client).get<GetNowResponses, GetNowErrors, ThrowOnError>({
    responseType: 'json',
    url: '/now',
    ...options
});
