// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AuthorizeData, AuthorizeErrors, AuthorizeResponses, CancelOrderData, CancelOrderErrors, CancelOrderResponses, ChangePasswordData, ChangePasswordErrors, ChangePasswordResponses, GetChartsData, GetChartsErrors, GetChartsResponses, GetConversionRatesBatchData, GetConversionRatesBatchErrors, GetConversionRatesBatchResponses, GetConversionRateSingleData, GetConversionRateSingleErrors, GetConversionRateSingleResponses, GetDepthData, GetDepthErrors, GetDepthResponses, GetHistoryOrderData, GetHistoryOrderErrors, GetHistoryOrderResponses, GetLimitsData, GetLimitsErrors, GetLimitsResponses, GetOrderData, GetOrderErrors, GetOrderResponses, GetOrdersData, GetOrdersErrors, GetOrdersHistoryData, GetOrdersHistoryErrors, GetOrdersHistoryResponses, GetOrdersResponses, GetPositionsData, GetPositionsErrors, GetPositionsResponses, GetStateData, GetStateErrors, GetStateResponses, GetSymbolData, GetSymbolErrors, GetSymbolResponses, GetSymbolsData, GetSymbolsErrors, GetSymbolsResponses, GetTobData, GetTobErrors, GetTobResponses, GetTradesData, GetTradesErrors, GetTradesResponses, GetTransfersHistoryData, GetTransfersHistoryErrors, GetTransfersHistoryResponses, HealthCheckData, HealthCheckErrors, HealthCheckResponses, LogoutData, LogoutErrors, LogoutResponses, ModifyOrderData, ModifyOrderErrors, ModifyOrderResponses, ModifyOrderSltpData, ModifyOrderSltpErrors, ModifyOrderSltpResponses, ModifyPositionSltpData, ModifyPositionSltpErrors, ModifyPositionSltpResponses, PlaceOrderData, PlaceOrderErrors, PlaceOrderResponses, ProbeMarginData, ProbeMarginErrors, ProbeMarginResponses, RefreshTokenData, RefreshTokenErrors, RefreshTokenResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * User authentication
 *
 * Username and password authentication.
 *
 * `Weight` 5.
 *
 */
export const authorize = <ThrowOnError extends boolean = false>(options: Options<AuthorizeData, ThrowOnError>): RequestResult<AuthorizeResponses, AuthorizeErrors, ThrowOnError> => (options.client ?? client).post<AuthorizeResponses, AuthorizeErrors, ThrowOnError>({
    responseType: 'json',
    url: '/authorize',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Refresh API token
 *
 * Refresh API token.
 *
 * `Weight` 5.
 *
 */
export const refreshToken = <ThrowOnError extends boolean = false>(options: Options<RefreshTokenData, ThrowOnError>): RequestResult<RefreshTokenResponses, RefreshTokenErrors, ThrowOnError> => (options.client ?? client).post<RefreshTokenResponses, RefreshTokenErrors, ThrowOnError>({
    responseType: 'json',
    url: '/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Logout
 *
 * Send logout.
 *
 * `Weight` 2.
 *
 */
export const logout = <ThrowOnError extends boolean = false>(options: Options<LogoutData, ThrowOnError>): RequestResult<LogoutResponses, LogoutErrors, ThrowOnError> => (options.client ?? client).post<LogoutResponses, LogoutErrors, ThrowOnError>({
    responseType: 'json',
    url: '/logout',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Change password
 *
 * Change trading account password.
 *
 * `Weight` 5.
 *
 */
export const changePassword = <ThrowOnError extends boolean = false>(options: Options<ChangePasswordData, ThrowOnError>): RequestResult<ChangePasswordResponses, ChangePasswordErrors, ThrowOnError> => (options.client ?? client).post<ChangePasswordResponses, ChangePasswordErrors, ThrowOnError>({
    responseType: 'json',
    url: '/password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Rate limits
 *
 * Get rate limits and unfilled order count limits.
 *
 * `Weight` 5.
 *
 */
export const getLimits = <ThrowOnError extends boolean = false>(options: Options<GetLimitsData, ThrowOnError>): RequestResult<GetLimitsResponses, GetLimitsErrors, ThrowOnError> => (options.client ?? client).get<GetLimitsResponses, GetLimitsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/limits',
    ...options
});

/**
 * Get symbol
 *
 * Returns configuration for symbol.
 *
 * `Weight` 2.
 *
 */
export const getSymbol = <ThrowOnError extends boolean = false>(options: Options<GetSymbolData, ThrowOnError>): RequestResult<GetSymbolResponses, GetSymbolErrors, ThrowOnError> => (options.client ?? client).get<GetSymbolResponses, GetSymbolErrors, ThrowOnError>({
    responseType: 'json',
    url: '/symbols/get/{symbolName}',
    ...options
});

/**
 * Get all symbols
 *
 * Returns configuration for all available symbols.
 *
 * `Weight` 20.
 *
 */
export const getSymbols = <ThrowOnError extends boolean = false>(options: Options<GetSymbolsData, ThrowOnError>): RequestResult<GetSymbolsResponses, GetSymbolsErrors, ThrowOnError> => (options.client ?? client).get<GetSymbolsResponses, GetSymbolsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/symbols/query',
    ...options
});

/**
 * Trading account state
 *
 * Get trading account information.
 *
 * Consider using WebSocket API instead, as it can decrease the workload on the servers.
 *
 * `Weight` 20.
 *
 */
export const getState = <ThrowOnError extends boolean = false>(options: Options<GetStateData, ThrowOnError>): RequestResult<GetStateResponses, GetStateErrors, ThrowOnError> => (options.client ?? client).post<GetStateResponses, GetStateErrors, ThrowOnError>({
    responseType: 'json',
    url: '/account/state',
    ...options
});

/**
 * Open orders
 *
 * Get working and inactive orders.
 *
 * Consider using WebSocket API instead, as it can decrease the workload on the servers.
 *
 * `Weight` 20.
 *
 */
export const getOrders = <ThrowOnError extends boolean = false>(options: Options<GetOrdersData, ThrowOnError>): RequestResult<GetOrdersResponses, GetOrdersErrors, ThrowOnError> => (options.client ?? client).post<GetOrdersResponses, GetOrdersErrors, ThrowOnError>({
    responseType: 'json',
    url: '/orders/open',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get single open order by order id
 *
 * Get working or inactive order.
 *
 * Consider using WebSocket API instead, as it can decrease the workload on the servers.
 *
 * `Weight` 4.
 *
 */
export const getOrder = <ThrowOnError extends boolean = false>(options: Options<GetOrderData, ThrowOnError>): RequestResult<GetOrderResponses, GetOrderErrors, ThrowOnError> => (options.client ?? client).post<GetOrderResponses, GetOrderErrors, ThrowOnError>({
    responseType: 'json',
    url: '/orders/open/single',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Orders history
 *
 * Get order history for an account. Returned orders will have a final status (`Rejected`,
 * `Filled`, `Cancelled` and `Expired`).
 *
 * `Weight` 20.
 *
 */
export const getOrdersHistory = <ThrowOnError extends boolean = false>(options: Options<GetOrdersHistoryData, ThrowOnError>): RequestResult<GetOrdersHistoryResponses, GetOrdersHistoryErrors, ThrowOnError> => (options.client ?? client).post<GetOrdersHistoryResponses, GetOrdersHistoryErrors, ThrowOnError>({
    responseType: 'json',
    url: '/orders/completed',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get single historical order
 *
 * Returns single order in a final state (Rejected, Filled, Cancelled and Expired). Available history depths is limited due to performance reasons.
 *
 * `Weight` 20.
 *
 */
export const getHistoryOrder = <ThrowOnError extends boolean = false>(options: Options<GetHistoryOrderData, ThrowOnError>): RequestResult<GetHistoryOrderResponses, GetHistoryOrderErrors, ThrowOnError> => (options.client ?? client).post<GetHistoryOrderResponses, GetHistoryOrderErrors, ThrowOnError>({
    responseType: 'json',
    url: '/orders/completed/single',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Place order
 *
 * Place a new order.
 *
 * `Weight` 1.
 *
 */
export const placeOrder = <ThrowOnError extends boolean = false>(options: Options<PlaceOrderData, ThrowOnError>): RequestResult<PlaceOrderResponses, PlaceOrderErrors, ThrowOnError> => (options.client ?? client).post<PlaceOrderResponses, PlaceOrderErrors, ThrowOnError>({
    responseType: 'json',
    url: '/order',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Modify order
 *
 * Modify an existing order.
 *
 * `Weight` 1.
 *
 */
export const modifyOrder = <ThrowOnError extends boolean = false>(options: Options<ModifyOrderData, ThrowOnError>): RequestResult<ModifyOrderResponses, ModifyOrderErrors, ThrowOnError> => (options.client ?? client).put<ModifyOrderResponses, ModifyOrderErrors, ThrowOnError>({
    url: '/order',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Cancel order
 *
 * Cancel an existing order.
 *
 * `Weight` 1.
 *
 */
export const cancelOrder = <ThrowOnError extends boolean = false>(options: Options<CancelOrderData, ThrowOnError>): RequestResult<CancelOrderResponses, CancelOrderErrors, ThrowOnError> => (options.client ?? client).delete<CancelOrderResponses, CancelOrderErrors, ThrowOnError>({ url: '/order/{orderId}', ...options });

/**
 * Modify stop loss and/or take profit of order
 *
 * Modify stop loss and/or take profit of order.
 *
 * `Weight` 1.
 *
 */
export const modifyOrderSltp = <ThrowOnError extends boolean = false>(options: Options<ModifyOrderSltpData, ThrowOnError>): RequestResult<ModifyOrderSltpResponses, ModifyOrderSltpErrors, ThrowOnError> => (options.client ?? client).put<ModifyOrderSltpResponses, ModifyOrderSltpErrors, ThrowOnError>({
    responseType: 'json',
    url: '/order/sltp',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Modify stop loss and/or take profit of position
 *
 * Modify stop loss and/or take profit of position.
 *
 * `Weight` 1.
 *
 */
export const modifyPositionSltp = <ThrowOnError extends boolean = false>(options: Options<ModifyPositionSltpData, ThrowOnError>): RequestResult<ModifyPositionSltpResponses, ModifyPositionSltpErrors, ThrowOnError> => (options.client ?? client).put<ModifyPositionSltpResponses, ModifyPositionSltpErrors, ThrowOnError>({
    responseType: 'json',
    url: '/sltp',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Open positions
 *
 * Get positions for an account.
 *
 * Consider using WebSocket API instead, as it can decrease the workload on the servers.
 *
 * `Weight` 20.
 *
 */
export const getPositions = <ThrowOnError extends boolean = false>(options: Options<GetPositionsData, ThrowOnError>): RequestResult<GetPositionsResponses, GetPositionsErrors, ThrowOnError> => (options.client ?? client).post<GetPositionsResponses, GetPositionsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/positions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Trades history
 *
 * Get a list of trades.
 *
 * `Weight` 20.
 *
 */
export const getTrades = <ThrowOnError extends boolean = false>(options: Options<GetTradesData, ThrowOnError>): RequestResult<GetTradesResponses, GetTradesErrors, ThrowOnError> => (options.client ?? client).post<GetTradesResponses, GetTradesErrors, ThrowOnError>({
    responseType: 'json',
    url: '/trades',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Charts
 *
 * Request for history chart bars.
 *
 * `Weight` 5.
 *
 */
export const getCharts = <ThrowOnError extends boolean = false>(options: Options<GetChartsData, ThrowOnError>): RequestResult<GetChartsResponses, GetChartsErrors, ThrowOnError> => (options.client ?? client).post<GetChartsResponses, GetChartsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/charts',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Depth of the market
 *
 * Get current depth of market for the instrument.
 * `Weight` 25.
 *
 */
export const getDepth = <ThrowOnError extends boolean = false>(options: Options<GetDepthData, ThrowOnError>): RequestResult<GetDepthResponses, GetDepthErrors, ThrowOnError> => (options.client ?? client).get<GetDepthResponses, GetDepthErrors, ThrowOnError>({
    responseType: 'json',
    url: '/depth/{symbolName}',
    ...options
});

/**
 * Get top of the book
 *
 * Get the best bid and ask of the instrument.
 *
 * `Weight` 2.
 *
 */
export const getTob = <ThrowOnError extends boolean = false>(options: Options<GetTobData, ThrowOnError>): RequestResult<GetTobResponses, GetTobErrors, ThrowOnError> => (options.client ?? client).get<GetTobResponses, GetTobErrors, ThrowOnError>({
    responseType: 'json',
    url: '/quote/{symbolName}',
    ...options
});

/**
 * Cash/asset transfers history
 *
 * Get cash/asset transfers history for an account.
 *
 * `Weight` 20.
 *
 */
export const getTransfersHistory = <ThrowOnError extends boolean = false>(options: Options<GetTransfersHistoryData, ThrowOnError>): RequestResult<GetTransfersHistoryResponses, GetTransfersHistoryErrors, ThrowOnError> => (options.client ?? client).post<GetTransfersHistoryResponses, GetTransfersHistoryErrors, ThrowOnError>({
    responseType: 'json',
    url: '/transfers',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get single conversion rate
 *
 * Get conversion rate for a single currency pair.
 *
 * `Weight` 2.
 *
 */
export const getConversionRateSingle = <ThrowOnError extends boolean = false>(options: Options<GetConversionRateSingleData, ThrowOnError>): RequestResult<GetConversionRateSingleResponses, GetConversionRateSingleErrors, ThrowOnError> => (options.client ?? client).post<GetConversionRateSingleResponses, GetConversionRateSingleErrors, ThrowOnError>({
    responseType: 'json',
    url: '/conversion-rate/single',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get conversion rates (batch)
 *
 * Get conversion rates for multiple currency pairs.
 *
 * Maximum 100 items per request.
 *
 * `Weight` 5.
 *
 */
export const getConversionRatesBatch = <ThrowOnError extends boolean = false>(options: Options<GetConversionRatesBatchData, ThrowOnError>): RequestResult<GetConversionRatesBatchResponses, GetConversionRatesBatchErrors, ThrowOnError> => (options.client ?? client).post<GetConversionRatesBatchResponses, GetConversionRatesBatchErrors, ThrowOnError>({
    responseType: 'json',
    url: '/conversion-rate/batch',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Probe margin requirement
 *
 * Check margin requirement for a potential order without placing it.
 *
 * `Weight` 1.
 *
 */
export const probeMargin = <ThrowOnError extends boolean = false>(options: Options<ProbeMarginData, ThrowOnError>): RequestResult<ProbeMarginResponses, ProbeMarginErrors, ThrowOnError> => (options.client ?? client).post<ProbeMarginResponses, ProbeMarginErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/margin/probe',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Health check
 *
 * Returns current time and server version.
 *
 * `Weight` 1.
 *
 */
export const healthCheck = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckData, ThrowOnError>): RequestResult<HealthCheckResponses, HealthCheckErrors, ThrowOnError> => (options?.client ?? client).get<HealthCheckResponses, HealthCheckErrors, ThrowOnError>({
    responseType: 'json',
    url: '/now',
    ...options
});
