// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'https://<IP_address>:<port>/api/v1' | (string & {});
};

/**
 * ApiErrorCode
 *
 * Numeric error code, returned as a string. The following table lists all possible values:
 * | Code | Description                          | |------|--------------------------------------| | "0"  | Successful operation                 | | "1"  | Not found                            | | "2"  | Server is not ready                  | | "3"  | Invalid parameter                    | | "4"  | Invalid target                       | | "5"  | Invalid 'NextToken'                  | | "6"  | Invalid header                       | | "7"  | Invalid version                      | | "8"  | Internal error                       | | "9"  | Dependencies exist                   | | "10" | Already exists                       | | "11" | Invalid payload                      | | "12" | Not allowed                          | | "13" | Operation not permitted              | | "14" | Business logic error                 | | "15" | Invalid Id                           | | "16" | Data changed                         | | "17" | Identifier cannot be reused          | | "100"| No market depth                      | | "101"| Invalid market depth                 |
 */
export type ApiErrorCode = string;

/**
 * A simplified representation of RFC 9457 "Problem Details for HTTP APIs"
 */
export type ProblemDetails = {
    /**
     * A short, human-readable localised summary of the problem type.
     */
    title: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    code?: ApiErrorCode;
};

/**
 * OkStatus
 *
 * Status will always be `ok`.
 */
export type OkStatus = 'ok';

/**
 * ErrorStatus
 *
 * Status will always be `error`.
 */
export type ErrorStatus = 'error';

/**
 * ApiToken
 *
 * API token.
 */
export type ApiToken = {
    /**
     * Trading account ID associated with this token.
     */
    account: number;
    /**
     * API token acts as a session ID that the application uses for making
     * requests. This token should be protected as if it were user
     * credentials.
     *
     */
    token: string;
    /**
     * Signing token used as the secret key when preparing HMAC signatures
     * for API requests. This token should be protected as if it were user
     * credentials.
     *
     */
    signingToken: string;
    /**
     * The time when the token is expired is represented as the number of
     * microseconds since the Unix epoch (00:00:00 UTC on 1 January 1970).
     *
     */
    expiration: number;
};

/**
 * Locale
 *
 * Locale (language) unique identifier.
 */
export type Locale = 'en';

/**
 * Side.
 */
export type Side = 'buy' | 'sell';

export type TradeType = 'In' | 'Out' | 'InOut';

/**
 * Quantity (in lots).
 */
export type QuantityLots = number;

/**
 * Quantity in units (`lots` * `lot size`).
 */
export type QuantityUnits = number;

/**
 * AccountSummaryRow
 *
 * Localised Account Summary Row configuration.
 */
export type AccountSummaryRow = Array<AccountSummaryRowItem>;

/**
 * AccountSummaryRowItem
 */
export type AccountSummaryRowItem = {
    /**
     * Unique Account Summary Row item identifier.
     */
    id: string;
    /**
     * Localised Account Summary Row item title.
     */
    title: string;
};

/**
 * AccountManager
 *
 * Localised Account Manager's tables configuration.
 *
 */
export type AccountManager = Array<AccountManagerTable>;

/**
 * AccountManagerColumn
 */
export type AccountManagerColumn = {
    id: string;
    /**
     * Localised title of a column.
     */
    title: string;
    /**
     * Tooltip that is shown on mouse hover.
     */
    tooltip?: string;
    /**
     * The cell value alignment. Default value is `left`.
     */
    alignment?: 'left' | 'right';
    /**
     * The first character of each word in the sentence will be capitalized. The rest of the symbols appearance does not change.
     */
    isCapitalize?: boolean;
};

/**
 * AccountManagerTable
 */
export type AccountManagerTable = {
    id: string;
    /**
     * Localised title of a table.
     */
    title?: string;
    columns: Array<AccountManagerColumn>;
};

/**
 * Duration
 *
 * Single order duration option (Time-in-Force).
 */
export type Duration = {
    /**
     * Duration identifier.
     */
    id: string;
    /**
     * Localised title.
     */
    title: string;
    /**
     * Display date control in Order Ticket for this duration type.
     */
    hasDatePicker?: boolean;
    /**
     * Display time control in Order Ticket for this duration type.
     */
    hasTimePicker?: boolean;
    /**
     * Default duration. Only one duration object in the durations array can have a `true` value for this field. The default duration will be used when the user places orders in the silent mode and it will be the selected one when the user opens the Order dialog for the first time.
     */
    default?: boolean;
    /**
     * An optional array of order types to which the duration will be applied.
     */
    supportedOrderTypes: Array<'market' | 'stop' | 'limit' | 'stoplimit'>;
};

/**
 * Durations
 *
 * Localised array of order durations (Time-in-Force).
 */
export type Durations = Array<Duration>;

/**
 * Config
 */
export type Config = {
    accountSummaryRow?: AccountSummaryRow;
    accountManager?: AccountManager;
    durations?: Durations;
    orderCustomFields?: OrderCustomFields;
    orderHistoryCustomFields?: OrderHistoryCustomFields;
    positionCustomFields?: PositionCustomFields;
    netPositionCustomFields?: PositionCustomFields;
    individualPositionCustomFields?: PositionCustomFields;
    pullingInterval?: PullingInterval;
};

/**
 * PullingInterval
 *
 * Time intervals in milliseconds to pull data from the server.
 * Please note: if the pulling interval is set above the maximum value then the maximum value will be used explicitly.
 *
 */
export type PullingInterval = {
    /**
     * Time interval in milliseconds to request quote and level 2 depth updates.
     */
    quotes?: number;
    /**
     * Time interval in milliseconds to request orders.
     */
    orders?: number;
    /**
     * Time interval in milliseconds to request positions.
     */
    positions?: number;
    /**
     * Time interval in milliseconds to update Account manager tables.
     */
    accountManager?: number;
    /**
     * Time interval in milliseconds to request balances.
     */
    balances?: number;
};

/**
 * PositionCustomFields
 *
 * Position columns to be displayed in the positions table of the Account manager.
 *
 */
export type PositionCustomFields = Array<AccountManagerColumn>;

/**
 * OrderCustomFields
 *
 * Order columns to be displayed in the orders table of the Account manager.
 *
 */
export type OrderCustomFields = Array<AccountManagerColumn>;

/**
 * OrderHistoryCustomFields
 *
 * History columns to be displayed in the history table of the Account manager.
 *
 */
export type OrderHistoryCustomFields = Array<AccountManagerColumn>;

export type Session = {
    /**
     * Week day.
     */
    d: 'Mon' | 'Tue' | 'Wed' | 'Thu' | 'Fri' | 'Sat' | 'Sun';
    /**
     * Open time.
     */
    s: string;
    /**
     * Close time.
     */
    e: string;
};

export type Symbol = {
    /**
     * Symbol name.
     */
    n: string;
    /**
     * Entity version.
     */
    v: number;
    /**
     * Symbol description.
     */
    d: string;
    /**
     * Exchange for exchange-traded financial instruments.
     */
    ex?: string;
    /**
     * Pricing decimal precision.
     */
    dp: number;
    /**
     * Quantity of a stock, commodity, financial instrument, or units of base currency in 1 lot.
     */
    l: number;
    /**
     * Tick value (monetary value of 1 tick price change).
     */
    tv?: number;
    /**
     * Tick size (the lowest allowed increment of a price change).
     */
    tz?: number;
    /**
     * Trade mode.
     */
    tm: 'Disabled' | 'LongOnly' | 'ShortOnly' | 'CloseOnly' | 'Full';
    /**
     * Minimum order size (in lots, up to 8 decimal places).
     */
    min: number;
    /**
     * Maximum order size (in lots, up to 8 decimal places).
     */
    max: number;
    /**
     * Order size increment (in lots, up to 8 decimal places).
     */
    i: number;
    /**
     * Maximum total position size (in lots, up to 8 decimal places). 0 - no limit.
     */
    pos?: number;
    /**
     * Pricing decimal precision for base currency.
     */
    bdp: number;
    /**
     * Pricing decimal precision for profit currency.
     */
    pdp: number;
    /**
     * Pricing decimal precision for margin currency.
     */
    mdp: number;
    /**
     * true - market orders are allowed, false - market orders are prohibited.
     */
    M: boolean;
    /**
     * true - limit orders are allowed, false - limit orders are prohibited.
     */
    L: boolean;
    /**
     * true - stop orders are allowed, false - stop orders are prohibited.
     */
    S: boolean;
    /**
     * true - stop limit orders are allowed, false - stop limit orders are prohibited.
     */
    SLi: boolean;
    /**
     * true - stop loss orders are allowed, false - stop loss orders are prohibited.
     */
    SLo: boolean;
    /**
     * true - take profit orders are allowed, false - take profit orders are prohibited.
     */
    TP: boolean;
    /**
     * true - close by/close all orders are allowed, false - close by/close all orders are prohibited.
     */
    CB: boolean;
    /**
     * Base currency.
     */
    b: string;
    /**
     * Profit currency.
     */
    p: string;
    /**
     * Margin currency.
     */
    m: string;
    /**
     * true - 'Fill Or Kill' orders are allowed, false - 'Fill Or Kill' orders are prohibited.
     */
    fok: boolean;
    /**
     * true - 'Immediate or Cancel' orders are allowed, false - 'Immediate or Cancel' orders are prohibited.
     */
    ioc: boolean;
    /**
     * true - 'Good till Cancelled' orders are allowed, false - 'Good till Cancelled' orders are prohibited.
     */
    gtc: boolean;
    /**
     * true - 'Good till Date' orders are allowed, false - 'Good till Date' orders are prohibited.
     */
    gtd: boolean;
    /**
     * true - day orders are allowed, false - day orders are prohibited.
     */
    day: boolean;
    /**
     * true - 'Valid For Milliseconds' orders are allowed, false - 'Valid For Milliseconds' orders are prohibited.
     */
    ms: boolean;
    /**
     * Quote sessions.
     */
    q: Array<Session>;
    /**
     * Trade sessions.
     */
    t: Array<Session>;
    /**
     * Swap rate for long positions.
     */
    swL: number;
    /**
     * Swap rate for short positions.
     */
    swS: number;
    /**
     * Swap rate multiplier for Sunday.
     */
    swSun: number;
    /**
     * Swap rate multiplier for Monday.
     */
    swMon: number;
    /**
     * Swap rate multiplier for Tuesday.
     */
    swTue: number;
    /**
     * Swap rate multiplier for Wednesday.
     */
    swWed: number;
    /**
     * Swap rate multiplier for Thursday.
     */
    swThu: number;
    /**
     * Swap rate multiplier for Friday.
     */
    swFri: number;
    /**
     * Swap rate multiplier for Saturday.
     */
    swSat: number;
    /**
     * Swap calculation mode.
     */
    swM: 'Disabled' | 'Points' | 'BaseCurrency' | 'ProfitCurrency' | 'MarginCurrency' | 'AccountCurrency' | 'InterestCurrent' | 'InterestOpen' | 'Reopen';
    /**
     * Number of days in year for swap calculation (360 or 365).
     */
    swYd: number;
    /**
     * Swap intraday starting time in HH:MM:SS format. Only present when `swI` is not `EndOfDay`.
     */
    swSt?: string;
    /**
     * Swap charge interval. When set to `EndOfDay`, swap is charged once at the end of the trading day and `swSt` field is not included. When set to an intraday value, swap is charged at regular intervals starting from the time specified in `swSt`.
     */
    swI: 'EndOfDay' | 'IntradayOncePerFullDay' | 'IntradayTwicePerFullDay' | 'IntradayThreeTimesPerFullDay' | 'IntradayFourTimesPerFullDay';
};

export type SymbolCollection = {
    symbols: Array<Symbol>;
    /**
     * A token indicating there are more results available. If there are no more results, no token is included in the response. The value of `nextToken` is a unique pagination token for each page. To retrieve the next page of results, make the call again using the returned token. Keep all other arguments unchanged. Using an expired pagination token results in an `412 Precondition Failed` error.
     */
    nextToken?: string;
};

export type WorkingOrdersCollection = {
    orders: Array<Order>;
    /**
     * A token indicating there are more results available. If there are no more results, no token is included in the response. The value of `nextToken` is a unique pagination token for each page. To retrieve the next page of results, make the call again using the returned token. Keep all other arguments unchanged. Using an expired pagination token results in an `412 Precondition Failed` error.
     */
    nextToken?: string;
};

/**
 * String constants to describe an order status.
 *
 * Status  | Description
 * ----------|-------------
 * Inactive  | Stop Loss or Take Profit order is created but waiting for a base order to be filled.
 * Working   | Order is created and active but not executed yet.
 * PartiallyFilled    | Order is partially filled and still active.
 * Filled    | Order is fully filled.
 * Cancelled  | Order has been cancelled.
 * Rejected  | Order has been rejected.
 * Expired  | Order has expired.
 *
 */
export type OrderStatus = 'Inactive' | 'Working' | 'PartiallyFilled' | 'Filled' | 'Cancelled' | 'Rejected' | 'Expired';

/**
 * Order
 */
export type Order = {
    /**
     * Order unique identifier.
     */
    id: number;
    s: SymbolName;
    q: QuantityLots;
    S: Side;
    t: OrderType;
    /**
     * Filled volume (in lots).
     */
    fq?: number;
    /**
     * Average price of order fills (if any).
     *
     */
    ap?: number;
    /**
     * Limit price for limit or stop limit orders only.
     */
    lp?: number;
    /**
     * Stop price for stop or stop limit orders only.
     */
    sp?: number;
    /**
     * Identifier of a parent order. Should be set only for bracket orders.
     *
     */
    poi?: number;
    /**
     * Identifier of a parent position. Should be set only for bracket orders.
     *
     */
    ppi?: number;
    tif: TimeInForce;
    /**
     * If `tif` is `gtd` - microseconds since the Unix epoch; if `tif` is `ms` - milliseconds since order placement.
     */
    tt?: number;
    /**
     * Date/time when the order was created (microseconds since the Unix epoch).
     */
    C: number;
    /**
     * Date/time when the order was last modified (microseconds since the Unix epoch).
     */
    M: number;
    st: OrderStatus;
    ct?: OrderComment;
    /**
     * Stop Loss order unique identifier (if SL is set)
     */
    slid?: number;
    /**
     * Take Profit order unique identifier (if TP is set)
     */
    tpid?: number;
};

/**
 * CustomFieldsValueItem
 */
export type CustomFieldsValueItem = {
    /**
     * Column identifier.
     */
    id: string;
    /**
     * Localised column value.
     */
    v: string;
};

/**
 * OrderInformationalMessage
 *
 * Informational message description, that may be displayed for the order in the client terminal.
 *
 */
export type OrderInformationalMessage = {
    /**
     * Message text.
     */
    m?: string;
    /**
     * Message severity.
     */
    s: 'info' | 'warn' | 'err';
};

/**
 * Candle interval.
 */
export type CandleInterval = '1M' | '5M' | '15M' | '30M' | '1H' | '4H' | 'D' | 'W' | 'M';

export type AccountState = {
    /**
     * Account balance.
     */
    b: number;
    /**
     * Account credit.
     */
    C: number;
    /**
     * Unrealised profit/loss.
     */
    pl: number;
    /**
     * Equity. It is calculated as `balance` + `credit` + `unrealizedPL` + `collateral`.
     */
    e: number;
    /**
     * Margin requirements for account.
     */
    m: number;
    /**
     * Exchange Assets.
     */
    as: number;
    /**
     * Exchange Liabilities.
     */
    ls: number;
    /**
     * Account currency
     */
    c: string;
    /**
     * Market value of collateral adjusted by liquidity margin rate.
     */
    a?: number;
};

/**
 * PlaceOrder
 */
export type PlaceOrder = {
    s: SymbolName;
    q: QuantityLots;
    S: Side;
    t: OrderType;
    /**
     * Limit price for limit or stop limit order.
     */
    lp?: number;
    /**
     * Stop price for stop or stop limit order.
     */
    sp?: number;
    tif: TimeInForce;
    /**
     * If `tif` is `GTD` - microseconds since the Unix epoch; if `tif` is `Ms` - milliseconds since order placement.
     */
    tt?: number;
    /**
     * Position id.
     */
    pi?: number;
    /**
     * PositionBy id.
     */
    pbi?: number;
    /**
     * Stop loss price.
     */
    sl?: number;
    /**
     * Take profit price.
     */
    tp?: number;
    ct?: OrderComment;
};

/**
 * ModifyOrder
 */
export type ModifyOrder = {
    /**
     * Order unique identifier.
     */
    id: number;
    q?: QuantityLots;
    /**
     * Limit price for limit or stop limit order.
     */
    lp?: number;
    /**
     * Stop price for stop or stop limit order.
     */
    sp?: number;
};

/**
 * Modify position's stop loss and/or take profit
 */
export type ModifyPositionSltp = {
    /**
     * Position unique identifier.
     */
    id: number;
    /**
     * Stop loss price. If not set, stop loss order is cancelled.
     */
    sl?: number;
    /**
     * Take profit price. If not set, take profit order is cancelled.
     */
    tp?: number;
};

/**
 * Modify order's stop loss and/or take profit
 */
export type ModifyOrderSltp = {
    /**
     * Order unique identifier.
     */
    id?: number;
    /**
     * Stop loss price. If not set, stop loss order is cancelled.
     */
    sl?: number;
    /**
     * Take profit price. If not set, take profit order is cancelled.
     */
    tp?: number;
};

export type ModifySltpResult = {
    /**
     * StopLoss order unique identifier.
     */
    slid?: number;
    /**
     * StopLoss order unique identifier.
     */
    tpid?: number;
};

/**
 * Position
 */
export type Position = {
    /**
     * Position unique identifier.
     */
    id: number;
    s: SymbolName;
    q: QuantityLots;
    Q: QuantityUnits;
    S: Side;
    /**
     * Volume-weighted average price (VWAP) of position trades.
     */
    p: number;
    /**
     * Stop loss price.
     */
    sl?: number;
    /**
     * Take profit price.
     */
    tp?: number;
    /**
     * Unrealised profit/loss.
     */
    pl: number;
    /**
     * Swaps.
     */
    sw: number;
    /**
     * Commission.
     */
    c: number;
    /**
     * Margin.
     */
    m: number;
    /**
     * Fees.
     */
    f: number;
    /**
     * Market price.
     */
    mp: number;
    /**
     * Date/time when the position was created (microseconds since the Unix epoch).
     */
    C: number;
    /**
     * Date/time when the position was last modified (microseconds since the Unix epoch).
     */
    M: number;
    /**
     * Unique identifier of the order which created the position.
     */
    Ci: number;
    /**
     * Unique identifier of the order which last modified the position.
     */
    Mi: number;
    /**
     * Profit-to-account-currency conversion rate at the time of the last update.
     */
    pC: number;
    /**
     * Margin-to-account-currency conversion rate at the time of the last update.
     */
    mC: number;
};

export type PositionsCollection = {
    positions: Array<Position>;
    /**
     * A token indicating there are more results available. If there are no more results, no token is included in the response. The value of `nextToken` is a unique pagination token for each page. To retrieve the next page of results, make the call again using the returned token. Keep all other arguments unchanged. Using an expired pagination token results in an `412 Precondition Failed` error.
     */
    nextToken?: string;
};

export type TradeCollection = {
    trades: Array<Trade>;
    /**
     * A token indicating there are more results available. If there are no more results, no token is included in the response. The value of `nextToken` is a unique pagination token for each page. To retrieve the next page of results, make the call again using the returned token. Keep all other arguments unchanged. Using an expired pagination token results in an `412 Precondition Failed` error.
     */
    nextToken?: string;
};

/**
 * Trade
 *
 * Trade.
 */
export type Trade = {
    /**
     * Trade unique identifier.
     */
    id: number;
    s: SymbolName;
    /**
     * Execution price.
     */
    p: number;
    /**
     * Execution time (microseconds since the Unix epoch).
     */
    t: number;
    q: QuantityLots;
    S: Side;
    /**
     * Unique identifier of the order that has been filled.
     */
    oi: number;
    /**
     * Unique identifier of the position that has been opened, modified or closed.
     */
    pi: number;
    /**
     * Position price.
     */
    pp: number;
    /**
     * Profit/loss.
     */
    pl: number;
    /**
     * Swaps.
     */
    sw: number;
    /**
     * Commission charged for the fill.
     */
    c: number;
    /**
     * Profit conversion rate (into account currency)
     */
    C: number;
    /**
     * Fee charged for the fill.
     */
    f: number;
    T: TradeType;
    ct?: TradeComment;
};

/**
 * Order type.
 */
export type OrderType = 'Market' | 'Stop' | 'Limit' | 'StopLimit' | 'CloseBy';

/**
 * Time in Force. Only `FOK` and `IOC` are valid values for `CloseBy` and `Market` orders.
 */
export type TimeInForce = 'FOK' | 'IOC' | 'GTC' | 'GTD' | 'Day' | 'Ms';

export type TransferCollection = {
    transfers: Array<TransferHistory>;
    /**
     * A token indicating there are more results available. If there are no more results, no token is included in the response. The value of `nextToken` is a unique pagination token for each page. To retrieve the next page of results, make the call again using the returned token. Keep all other arguments unchanged. Using an expired pagination token results in an `412 Precondition Failed` error.
     */
    nextToken?: string;
};

export type TransferType = 'Balance' | 'Credit' | 'Fee' | 'Adjustment' | 'Bonus' | 'CreditBonus' | 'Commission' | 'DailyCommission' | 'MonthlyCommission' | 'AgentCommission' | 'DailyAgentCommission' | 'MonthlyAgentCommission' | 'Interest' | 'Dividend' | 'FrankedDividend' | 'Tax' | 'StopoutCompensation' | 'StopoutCreditAdjustment';

/**
 * TransferHistory
 *
 * Cash transfer.
 */
export type TransferHistory = {
    /**
     * Transaction ID. Should be 0 for a new cash transfer.
     */
    id: number;
    /**
     * Amount.
     */
    a: number;
    T: TransferType;
    /**
     * Amount currency or asset name.
     */
    c: string;
    /**
     * Transaction date/time (microseconds since the Unix epoch).
     */
    t: number;
    ct?: TransferComment;
};

export type OrdersHistoryCollection = {
    orders: Array<Order>;
    /**
     * A token indicating there are more results available. If there are no more results, no token is included in the response. The value of `nextToken` is a unique pagination token for each page. To retrieve the next page of results, make the call again using the returned token. Keep all other arguments unchanged. Using an expired pagination token results in an `412 Precondition Failed` error.
     */
    nextToken?: string;
};

/**
 * Balances
 */
export type Balances = Array<Balance>;

/**
 * Balance
 */
export type Balance = {
    /**
     * Asset.
     */
    a: string;
    /**
     * Asset description.
     */
    d?: string;
    /**
     * Total amount of the balance.
     */
    t: number;
    /**
     * The balance available to the user.
     */
    av: number;
    /**
     * Liquidity margin rate. For example, if it is set to 0.5, only 50% of market value can be used for collateral purposes.
     */
    r?: number;
    /**
     * Market price (if applicable)
     */
    p?: number;
};

/**
 * Symbol name.
 */
export type SymbolName = string;

/**
 * Order comment.
 */
export type OrderComment = string;

/**
 * Trade comment.
 */
export type TradeComment = string;

/**
 * Transfer comment.
 */
export type TransferComment = string;

/**
 * Candle
 */
export type Candle = {
    /**
     * Bar start time (microseconds since the Unix epoch).
     */
    t: number;
    /**
     * Open price.
     */
    o: number;
    /**
     * High price.
     */
    h: number;
    /**
     * Low price.
     */
    l: number;
    /**
     * Close price.
     */
    c: number;
    /**
     * Volume.
     */
    v: number;
};

/**
 * CandlesResponse
 */
export type Candles = {
    s: SymbolName;
    i: CandleInterval;
    /**
     * Array of chart bars
     */
    d: Array<Candle>;
    /**
     * A token indicating there are more results available. If there are no more results, no token is included in the response. The value of `nextToken` is a unique pagination token for each page. To retrieve the next page of results, make the call again using the returned token. Keep all other arguments unchanged. Using an expired pagination token results in an `412 Precondition Failed` error.
     */
    nextToken?: string;
};

/**
 * Book
 *
 * Depth of market for an instrument.
 */
export type Book = {
    /**
     * Array of arrays with two numeric elements - price and volume. Sorted by `price` in ascending order.
     */
    a: Array<BookItem>;
    /**
     * Array of arrays with two numeric elements - price and volume. Sorted by `price` in descending order.
     */
    b: Array<BookItem>;
    /**
     * Ask high - highest ask price for the day.
     */
    ah?: number;
    /**
     * Ask low - lowest ask price for the day.
     */
    al?: number;
    /**
     * Bid high - highest bid price for the day.
     */
    bh?: number;
    /**
     * Bid low - lowest bid price for the day.
     */
    bl?: number;
    /**
     * Bid close - last bid price of the previous trading day.
     */
    bc?: number;
    /**
     * Ask close - last ask price of the previous trading day.
     */
    ac?: number;
};

/**
 * BookItem
 *
 * Array with two numeric elements - price and volume.
 */
export type BookItem = Array<number>;

/**
 * Quote
 *
 * Top of the book prices for an instrument.
 */
export type Quote = {
    s: SymbolName;
    /**
     * Best bid price.
     */
    bp: number;
    /**
     * Best bid size.
     */
    bs: number;
    /**
     * Best ask price.
     */
    ap: number;
    /**
     * Best ask size.
     */
    as: number;
    /**
     * Bid high - highest bid price for the day.
     */
    bh?: number;
    /**
     * Bid low - lowest bid price for the day.
     */
    bl?: number;
    /**
     * Ask high - highest ask price for the day.
     */
    ah?: number;
    /**
     * Ask low - lowest ask price for the day.
     */
    al?: number;
    /**
     * Bid close - last bid price of the previous trading day.
     */
    bc?: number;
    /**
     * Ask close - last ask price of the previous trading day.
     */
    ac?: number;
    /**
     * Timestamp (microseconds since the Unix epoch).
     */
    t: number;
};

/**
 * Limit
 */
export type Limit = {
    /**
     * Limit type.
     */
    t: 'weight' | 'order';
    /**
     * Interval: `S` - second, `M` - minute, `H` - hour, and `D` - day.
     *
     */
    i: 'S' | 'M' | 'H' | 'D';
    /**
     * Number of intervals.
     */
    n: number;
    /**
     * Limit value.
     */
    l: number;
};

/**
 * Limits
 *
 * Rate limits and unfilled order count limits.
 */
export type Limits = Array<Limit>;

/**
 * SuccessResponse
 */
export type SuccessResponse = {
    /**
     * Status will always be `ok`.
     */
    s: 'ok';
};

/**
 * Health check
 *
 * Health check (returns server version and current time).
 */
export type Now = {
    /**
     * Current server time (UTC).
     */
    now: string;
    /**
     * Server version.
     */
    version: string;
};

/**
 * Sorting in ascending (`asc`) or descending (`desc`) direction
 */
export type SortOrder = 'asc' | 'desc';

/**
 * Start of the period
 *
 * Timestamp (microseconds since the Unix epoch) of the start of the period.
 */
export type HistoryFrom = number;

/**
 * End of the period
 *
 * Timestamp (microseconds since the Unix epoch) of the end of the period. It can be in the future.
 */
export type HistoryTo = number;

/**
 * Filters for cash/asset transfers report
 *
 * Filters for cash/asset transfers report.
 */
export type TransferRequestFilter = {
    /**
     * The maximum number of results returned by the call. If more than 100 results is requested, the server will return 100 items.
     */
    maxResults?: number;
    sortOrder?: SortOrder;
    from?: HistoryFrom;
    to?: HistoryTo;
};

/**
 * Filters for open orders report
 *
 * Filters for open orders report
 */
export type OpenOrderRequestFilter = {
    /**
     * The maximum number of results returned by the call. If more than 100 results is requested, the server will return 100 items.
     */
    maxResults?: number;
    sortOrder?: SortOrder;
    symbolName?: SymbolName;
};

/**
 * Filters for open positions report
 *
 * Filters for open positions report
 */
export type OpenPositionRequestFilter = {
    /**
     * The maximum number of results returned by the call. If more than 100 results is requested, the server will return 100 items.
     */
    maxResults?: number;
    sortOrder?: SortOrder;
    symbolName?: SymbolName;
};

/**
 * Filters for trades report
 *
 * Filters for trades report.
 */
export type OrderHistoryPageRequestFilter = {
    /**
     * The maximum number of results returned by the call. If more than 100 results is requested, the server will return 100 items.
     */
    maxResults?: number;
    sortOrder?: SortOrder;
    symbolName?: SymbolName;
    from?: HistoryFrom;
    to?: HistoryTo;
};

/**
 * Filters for trades report
 *
 * Filters for trades report.
 */
export type TradeHistoryPageRequestFilter = {
    /**
     * The maximum number of results returned by the call. If more than 100 results is requested, the server will return 100 items.
     */
    maxResults?: number;
    sortOrder?: SortOrder;
    symbolName?: SymbolName;
    from?: HistoryFrom;
    to?: HistoryTo;
};

/**
 * ChartBars page request
 *
 * Filters for trades report.
 */
export type ChartBarsPageRequest = {
    /**
     * The expected number of results. Server can return more bars.
     */
    maxResults?: number;
    sortOrder?: SortOrder;
    symbolName: SymbolName;
    interval: CandleInterval;
    from?: HistoryFrom;
    to?: HistoryTo;
};

/**
 * Single order request
 *
 * Single order request
 */
export type SingleOrderRequest = {
    /**
     * Order unique identifier.
     */
    orderId: number;
};

/**
 * Single conversion rate request
 *
 * Request for a single conversion rate
 */
export type SingleConversionRateRequest = {
    /**
     * Source currency code
     */
    from: string;
    /**
     * Target currency code
     */
    to: string;
};

/**
 * Conversion rates batch request
 *
 * Array of currency pairs for conversion rates (maximum 100 items)
 */
export type ConversionRatesBatchRequest = Array<SingleConversionRateRequest>;

/**
 * Conversion rate
 *
 * Conversion rate value
 */
export type ConversionRate = {
    /**
     * Conversion rate (how many units of target currency per 1 unit of source currency)
     */
    rate: number;
};

/**
 * Conversion rate batch result
 *
 * Result for a single currency pair in batch request
 */
export type ConversionRateBatchResult = {
    /**
     * Operation success flag
     */
    s: boolean;
    /**
     * Conversion rate. Present only on success.
     */
    r?: number;
    /**
     * Human-readable details in case of an error
     */
    d?: string;
    /**
     * Error code in case of an error
     */
    c?: number;
};

/**
 * Conversion rates batch response
 *
 * Array of conversion rate results corresponding to input pairs
 */
export type ConversionRatesBatchResponse = Array<ConversionRateBatchResult>;

/**
 * Entity version.
 */
export type IfNoneMatch = string;

/**
 * Entity version.
 */
export type IfMatch = string;

/**
 * API token.
 */
export type ApiKey = string;

/**
 * Nonce (must be larger than previous nonces). Required if HMAC signature is generated using nonce.
 */
export type Nonce = string;

/**
 * Timestamp (microseconds since Unix epoch). Required if HMAC signature is generated using timestamp.
 */
export type Timestamp = string;

/**
 * HMAC signature.
 */
export type Signature = string;

/**
 * The `nextToken` returned by a previous call, which can be used to retrieve the next set of results.
 */
export type NextToken = string;

/**
 * Locale (language) unique identifier.
 */
export type Locale2 = Locale;

/**
 * Symbol name.
 */
export type SymbolName2 = string;

/**
 * Order unique identifier.
 */
export type OrderId = number;

/**
 * Symbol name.
 */
export type Symbol2 = string;

/**
 * Chart interval.
 */
export type Interval = '1M' | '5M' | '15M' | '30M' | '1H' | '4H' | 'D' | 'W' | 'M';

/**
 * Timestamp (microseconds since the Unix epoch) of the leftmost required bar, including `from`.
 *
 */
export type HistoryFrom2 = number;

/**
 * Timestamp (microseconds since the Unix epoch) of the rightmost required bar, including `to`. It can be in the future. In this case, the rightmost required bar is the latest available bar.
 *
 */
export type HistoryTo2 = number;

/**
 * The maximum number of results returned by the call. Ignored if `nextToken` is present.
 */
export type MaxResults = number;

export type PostAuthorizeData = {
    body: {
        /**
         * Trading account login.
         */
        login: number;
        /**
         * Optional broker/company name for validation. If provided, must match the company name associated with the user's group. Maximum length is 63 characters.
         */
        broker?: string;
    };
    headers: {
        /**
         * Nonce (must be larger than previous nonces). Required if HMAC signature is generated using nonce.
         */
        'X-YB-Nonce'?: string;
        /**
         * Timestamp (microseconds since Unix epoch). Required if HMAC signature is generated using timestamp.
         */
        'X-YB-Timestamp'?: string;
        /**
         * HMAC signature.
         */
        'X-YB-Sign': string;
        /**
         * Locale (language) unique identifier.
         */
        'X-YB-Locale'?: Locale;
    };
    path?: never;
    query?: never;
    url: '/authorize';
};

export type PostAuthorizeErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * IP address is banned
     */
    403: ProblemDetails;
    /**
     * Too many requests
     */
    429: ProblemDetails;
};

export type PostAuthorizeError = PostAuthorizeErrors[keyof PostAuthorizeErrors];

export type PostAuthorizeResponses = {
    /**
     * Successful operation
     */
    200: ApiToken;
};

export type PostAuthorizeResponse = PostAuthorizeResponses[keyof PostAuthorizeResponses];

export type PostRefreshData = {
    body: unknown;
    headers: {
        /**
         * API token.
         */
        'X-YB-API-Key': string;
        /**
         * Nonce (must be larger than previous nonces). Required if HMAC signature is generated using nonce.
         */
        'X-YB-Nonce'?: string;
        /**
         * Timestamp (microseconds since Unix epoch). Required if HMAC signature is generated using timestamp.
         */
        'X-YB-Timestamp'?: string;
        /**
         * HMAC signature.
         */
        'X-YB-Sign': string;
        /**
         * Locale (language) unique identifier.
         */
        'X-YB-Locale'?: Locale;
    };
    path?: never;
    query?: never;
    url: '/refresh';
};

export type PostRefreshErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * IP address is banned
     */
    403: ProblemDetails;
    /**
     * Too many requests
     */
    429: ProblemDetails;
};

export type PostRefreshError = PostRefreshErrors[keyof PostRefreshErrors];

export type PostRefreshResponses = {
    /**
     * Successful operation
     */
    200: ApiToken;
};

export type PostRefreshResponse = PostRefreshResponses[keyof PostRefreshResponses];

export type LogoutData = {
    body: unknown;
    headers: {
        /**
         * API token.
         */
        'X-YB-API-Key': string;
        /**
         * Nonce (must be larger than previous nonces). Required if HMAC signature is generated using nonce.
         */
        'X-YB-Nonce'?: string;
        /**
         * Timestamp (microseconds since Unix epoch). Required if HMAC signature is generated using timestamp.
         */
        'X-YB-Timestamp'?: string;
        /**
         * HMAC signature.
         */
        'X-YB-Sign': string;
        /**
         * Locale (language) unique identifier.
         */
        'X-YB-Locale'?: Locale;
    };
    path?: never;
    query?: never;
    url: '/logout';
};

export type LogoutErrors = {
    /**
     * IP address is banned
     */
    403: ProblemDetails;
    /**
     * Too many requests
     */
    429: ProblemDetails;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * Successful operation
     */
    200: SuccessResponse;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type PostPasswordData = {
    body: {
        /**
         * New password.
         */
        password: string;
    };
    headers: {
        /**
         * API token.
         */
        'X-YB-API-Key': string;
        /**
         * Nonce (must be larger than previous nonces). Required if HMAC signature is generated using nonce.
         */
        'X-YB-Nonce'?: string;
        /**
         * Timestamp (microseconds since Unix epoch). Required if HMAC signature is generated using timestamp.
         */
        'X-YB-Timestamp'?: string;
        /**
         * HMAC signature.
         */
        'X-YB-Sign': string;
        /**
         * Locale (language) unique identifier.
         */
        'X-YB-Locale'?: Locale;
    };
    path?: never;
    query?: never;
    url: '/password';
};

export type PostPasswordErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * IP address is banned
     */
    403: ProblemDetails;
    /**
     * Too many requests
     */
    429: ProblemDetails;
};

export type PostPasswordError = PostPasswordErrors[keyof PostPasswordErrors];

export type PostPasswordResponses = {
    /**
     * Successful operation
     */
    200: SuccessResponse;
};

export type PostPasswordResponse = PostPasswordResponses[keyof PostPasswordResponses];

export type GetLimitsData = {
    body?: never;
    headers: {
        /**
         * API token.
         */
        'X-YB-API-Key': string;
        /**
         * Locale (language) unique identifier.
         */
        'X-YB-Locale'?: Locale;
        /**
         * Entity version.
         */
        'If-None-Match'?: string;
    };
    path?: never;
    query?: never;
    url: '/limits';
};

export type GetLimitsErrors = {
    /**
     * IP address is banned
     */
    403: ProblemDetails;
    /**
     * Too many requests
     */
    429: ProblemDetails;
};

export type GetLimitsError = GetLimitsErrors[keyof GetLimitsErrors];

export type GetLimitsResponses = {
    /**
     * Successful operation
     */
    200: Limits;
};

export type GetLimitsResponse = GetLimitsResponses[keyof GetLimitsResponses];

export type GetSymbolData = {
    body?: never;
    headers: {
        /**
         * API token.
         */
        'X-YB-API-Key': string;
        /**
         * Locale (language) unique identifier.
         */
        'X-YB-Locale'?: Locale;
        /**
         * Entity version.
         */
        'If-None-Match'?: string;
    };
    path: {
        /**
         * Symbol name.
         */
        symbolName: string;
    };
    query?: never;
    url: '/symbols/get/{symbolName}';
};

export type GetSymbolErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * IP address is banned
     */
    403: ProblemDetails;
    /**
     * Entity not found at server
     */
    404: ProblemDetails;
    /**
     * Too many requests
     */
    429: ProblemDetails;
};

export type GetSymbolError = GetSymbolErrors[keyof GetSymbolErrors];

export type GetSymbolResponses = {
    /**
     * Successful operation
     */
    200: Symbol;
};

export type GetSymbolResponse = GetSymbolResponses[keyof GetSymbolResponses];

export type GetSymbolsData = {
    body?: never;
    headers: {
        /**
         * API token.
         */
        'X-YB-API-Key': string;
        /**
         * The `nextToken` returned by a previous call, which can be used to retrieve the next set of results.
         */
        'X-YB-NEXT-TOKEN'?: string;
        /**
         * Locale (language) unique identifier.
         */
        'X-YB-Locale'?: Locale;
        /**
         * Entity version.
         */
        'If-None-Match'?: string;
    };
    path?: never;
    query?: {
        /**
         * The maximum number of results returned by the call. Ignored if `nextToken` is present.
         */
        maxResults?: number;
        /**
         * Sorting by symbol name in ascending (`asc`) or descending (`desc`) direction. Ignored if `nextToken` is present.
         */
        sort?: 'asc' | 'desc';
    };
    url: '/symbols/query';
};

export type GetSymbolsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * IP address is banned
     */
    403: ProblemDetails;
    /**
     * Entity not found at server
     */
    404: ProblemDetails;
    /**
     * Precondition Failed
     */
    412: ProblemDetails;
    /**
     * Too many requests
     */
    429: ProblemDetails;
};

export type GetSymbolsError = GetSymbolsErrors[keyof GetSymbolsErrors];

export type GetSymbolsResponses = {
    /**
     * Successful operation
     */
    200: SymbolCollection;
};

export type GetSymbolsResponse = GetSymbolsResponses[keyof GetSymbolsResponses];

export type GetStateData = {
    body?: never;
    headers: {
        /**
         * API token.
         */
        'X-YB-API-Key': string;
        /**
         * Locale (language) unique identifier.
         */
        'X-YB-Locale'?: Locale;
    };
    path?: never;
    query?: never;
    url: '/account/state';
};

export type GetStateErrors = {
    /**
     * IP address is banned
     */
    403: ProblemDetails;
    /**
     * Too many requests
     */
    429: ProblemDetails;
};

export type GetStateError = GetStateErrors[keyof GetStateErrors];

export type GetStateResponses = {
    /**
     * Successful operation
     */
    200: AccountState;
};

export type GetStateResponse = GetStateResponses[keyof GetStateResponses];

export type GetBalancesData = {
    body?: never;
    headers: {
        /**
         * API token.
         */
        'X-YB-API-Key': string;
        /**
         * Locale (language) unique identifier.
         */
        'X-YB-Locale'?: Locale;
    };
    path?: never;
    query?: never;
    url: '/account/balances';
};

export type GetBalancesErrors = {
    /**
     * IP address is banned
     */
    403: ProblemDetails;
    /**
     * Too many requests
     */
    429: ProblemDetails;
};

export type GetBalancesError = GetBalancesErrors[keyof GetBalancesErrors];

export type GetBalancesResponses = {
    /**
     * Successful operation
     */
    200: Balances;
};

export type GetBalancesResponse = GetBalancesResponses[keyof GetBalancesResponses];

export type GetOrdersData = {
    body: OpenOrderRequestFilter;
    headers: {
        /**
         * API token.
         */
        'X-YB-API-Key': string;
        /**
         * Locale (language) unique identifier.
         */
        'X-YB-Locale'?: Locale;
        /**
         * The `nextToken` returned by a previous call, which can be used to retrieve the next set of results.
         */
        'X-YB-NEXT-TOKEN'?: string;
    };
    path?: never;
    query?: never;
    url: '/orders/open';
};

export type GetOrdersErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * IP address is banned
     */
    403: ProblemDetails;
    /**
     * Entity not found at server
     */
    404: ProblemDetails;
    /**
     * Too many requests
     */
    429: ProblemDetails;
};

export type GetOrdersError = GetOrdersErrors[keyof GetOrdersErrors];

export type GetOrdersResponses = {
    /**
     * Successful operation
     */
    200: WorkingOrdersCollection;
};

export type GetOrdersResponse = GetOrdersResponses[keyof GetOrdersResponses];

export type GetOrderData = {
    body: SingleOrderRequest;
    headers: {
        /**
         * API token.
         */
        'X-YB-API-Key': string;
        /**
         * Locale (language) unique identifier.
         */
        'X-YB-Locale'?: Locale;
    };
    path?: never;
    query?: never;
    url: '/orders/open/single';
};

export type GetOrderErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * IP address is banned
     */
    403: ProblemDetails;
    /**
     * Entity not found at server
     */
    404: ProblemDetails;
    /**
     * Too many requests
     */
    429: ProblemDetails;
};

export type GetOrderError = GetOrderErrors[keyof GetOrderErrors];

export type GetOrderResponses = {
    /**
     * Successful operation
     */
    200: Order;
};

export type GetOrderResponse = GetOrderResponses[keyof GetOrderResponses];

export type GetOrdersHistoryData = {
    body: OrderHistoryPageRequestFilter;
    headers: {
        /**
         * API token.
         */
        'X-YB-API-Key': string;
        /**
         * Locale (language) unique identifier.
         */
        'X-YB-Locale'?: Locale;
        /**
         * The `nextToken` returned by a previous call, which can be used to retrieve the next set of results.
         */
        'X-YB-NEXT-TOKEN'?: string;
    };
    path?: never;
    query?: never;
    url: '/orders/completed';
};

export type GetOrdersHistoryErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * IP address is banned
     */
    403: ProblemDetails;
    /**
     * Entity not found at server
     */
    404: ProblemDetails;
    /**
     * Precondition Failed
     */
    412: ProblemDetails;
    /**
     * Too many requests
     */
    429: ProblemDetails;
};

export type GetOrdersHistoryError = GetOrdersHistoryErrors[keyof GetOrdersHistoryErrors];

export type GetOrdersHistoryResponses = {
    /**
     * Successful operation
     */
    200: OrdersHistoryCollection;
};

export type GetOrdersHistoryResponse = GetOrdersHistoryResponses[keyof GetOrdersHistoryResponses];

export type GetHistoryOrderData = {
    body: SingleOrderRequest;
    headers: {
        /**
         * API token.
         */
        'X-YB-API-Key': string;
        /**
         * Locale (language) unique identifier.
         */
        'X-YB-Locale'?: Locale;
    };
    path?: never;
    query?: never;
    url: '/orders/completed/single';
};

export type GetHistoryOrderErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * IP address is banned
     */
    403: ProblemDetails;
    /**
     * Entity not found at server
     */
    404: ProblemDetails;
    /**
     * Precondition Failed
     */
    412: ProblemDetails;
    /**
     * Too many requests
     */
    429: ProblemDetails;
};

export type GetHistoryOrderError = GetHistoryOrderErrors[keyof GetHistoryOrderErrors];

export type GetHistoryOrderResponses = {
    /**
     * Successful operation
     */
    200: Order;
};

export type GetHistoryOrderResponse = GetHistoryOrderResponses[keyof GetHistoryOrderResponses];

export type PlaceOrderData = {
    body: PlaceOrder;
    headers: {
        /**
         * API token.
         */
        'X-YB-API-Key': string;
        /**
         * Nonce (must be larger than previous nonces). Required if HMAC signature is generated using nonce.
         */
        'X-YB-Nonce'?: string;
        /**
         * Timestamp (microseconds since Unix epoch). Required if HMAC signature is generated using timestamp.
         */
        'X-YB-Timestamp'?: string;
        /**
         * HMAC signature.
         */
        'X-YB-Sign': string;
        /**
         * Locale (language) unique identifier.
         */
        'X-YB-Locale'?: Locale;
    };
    path?: never;
    query?: never;
    url: '/order';
};

export type PlaceOrderErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * IP address is banned
     */
    403: ProblemDetails;
    /**
     * Too many requests
     */
    429: ProblemDetails;
};

export type PlaceOrderError = PlaceOrderErrors[keyof PlaceOrderErrors];

export type PlaceOrderResponses = {
    /**
     * Created
     */
    201: Order;
};

export type PlaceOrderResponse = PlaceOrderResponses[keyof PlaceOrderResponses];

export type ModifyOrderData = {
    body: ModifyOrder;
    headers: {
        /**
         * API token.
         */
        'X-YB-API-Key': string;
        /**
         * Nonce (must be larger than previous nonces). Required if HMAC signature is generated using nonce.
         */
        'X-YB-Nonce'?: string;
        /**
         * Timestamp (microseconds since Unix epoch). Required if HMAC signature is generated using timestamp.
         */
        'X-YB-Timestamp'?: string;
        /**
         * HMAC signature.
         */
        'X-YB-Sign': string;
        /**
         * Locale (language) unique identifier.
         */
        'X-YB-Locale'?: Locale;
    };
    path?: never;
    query?: never;
    url: '/order';
};

export type ModifyOrderErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * IP address is banned
     */
    403: ProblemDetails;
    /**
     * Too many requests
     */
    429: ProblemDetails;
};

export type ModifyOrderError = ModifyOrderErrors[keyof ModifyOrderErrors];

export type ModifyOrderResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type CancelOrderData = {
    body?: never;
    headers: {
        /**
         * API token.
         */
        'X-YB-API-Key': string;
        /**
         * Nonce (must be larger than previous nonces). Required if HMAC signature is generated using nonce.
         */
        'X-YB-Nonce'?: string;
        /**
         * Timestamp (microseconds since Unix epoch). Required if HMAC signature is generated using timestamp.
         */
        'X-YB-Timestamp'?: string;
        /**
         * HMAC signature.
         */
        'X-YB-Sign': string;
        /**
         * Locale (language) unique identifier.
         */
        'X-YB-Locale'?: Locale;
    };
    path: {
        /**
         * Order unique identifier.
         */
        orderId: number;
    };
    query?: never;
    url: '/order/{orderId}';
};

export type CancelOrderErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * IP address is banned
     */
    403: ProblemDetails;
    /**
     * Too many requests
     */
    429: ProblemDetails;
};

export type CancelOrderError = CancelOrderErrors[keyof CancelOrderErrors];

export type CancelOrderResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type ModifyOrderSltpData = {
    body: ModifyOrderSltp;
    headers: {
        /**
         * API token.
         */
        'X-YB-API-Key': string;
        /**
         * Nonce (must be larger than previous nonces). Required if HMAC signature is generated using nonce.
         */
        'X-YB-Nonce'?: string;
        /**
         * Timestamp (microseconds since Unix epoch). Required if HMAC signature is generated using timestamp.
         */
        'X-YB-Timestamp'?: string;
        /**
         * HMAC signature.
         */
        'X-YB-Sign': string;
        /**
         * Locale (language) unique identifier.
         */
        'X-YB-Locale'?: Locale;
    };
    path?: never;
    query?: never;
    url: '/order/sltp';
};

export type ModifyOrderSltpErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * IP address is banned
     */
    403: ProblemDetails;
    /**
     * Too many requests
     */
    429: ProblemDetails;
};

export type ModifyOrderSltpError = ModifyOrderSltpErrors[keyof ModifyOrderSltpErrors];

export type ModifyOrderSltpResponses = {
    /**
     * Successful operation
     */
    200: ModifySltpResult;
};

export type ModifyOrderSltpResponse = ModifyOrderSltpResponses[keyof ModifyOrderSltpResponses];

export type ModifyPositionSltpData = {
    body: ModifyPositionSltp;
    headers: {
        /**
         * API token.
         */
        'X-YB-API-Key': string;
        /**
         * Nonce (must be larger than previous nonces). Required if HMAC signature is generated using nonce.
         */
        'X-YB-Nonce'?: string;
        /**
         * Timestamp (microseconds since Unix epoch). Required if HMAC signature is generated using timestamp.
         */
        'X-YB-Timestamp'?: string;
        /**
         * HMAC signature.
         */
        'X-YB-Sign': string;
        /**
         * Locale (language) unique identifier.
         */
        'X-YB-Locale'?: Locale;
    };
    path?: never;
    query?: never;
    url: '/sltp';
};

export type ModifyPositionSltpErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * IP address is banned
     */
    403: ProblemDetails;
    /**
     * Too many requests
     */
    429: ProblemDetails;
};

export type ModifyPositionSltpError = ModifyPositionSltpErrors[keyof ModifyPositionSltpErrors];

export type ModifyPositionSltpResponses = {
    /**
     * Successful operation
     */
    200: ModifySltpResult;
};

export type ModifyPositionSltpResponse = ModifyPositionSltpResponses[keyof ModifyPositionSltpResponses];

export type GetPositionsData = {
    body: OpenPositionRequestFilter;
    headers: {
        /**
         * API token.
         */
        'X-YB-API-Key': string;
        /**
         * Locale (language) unique identifier.
         */
        'X-YB-Locale'?: Locale;
        /**
         * The `nextToken` returned by a previous call, which can be used to retrieve the next set of results.
         */
        'X-YB-NEXT-TOKEN'?: string;
    };
    path?: never;
    query?: never;
    url: '/positions';
};

export type GetPositionsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * IP address is banned
     */
    403: ProblemDetails;
    /**
     * Entity not found at server
     */
    404: ProblemDetails;
    /**
     * Precondition Failed
     */
    412: ProblemDetails;
    /**
     * Too many requests
     */
    429: ProblemDetails;
};

export type GetPositionsError = GetPositionsErrors[keyof GetPositionsErrors];

export type GetPositionsResponses = {
    /**
     * Successful operation
     */
    200: PositionsCollection;
};

export type GetPositionsResponse = GetPositionsResponses[keyof GetPositionsResponses];

export type GetTradesData = {
    body: TradeHistoryPageRequestFilter;
    headers: {
        /**
         * API token.
         */
        'X-YB-API-Key': string;
        /**
         * Locale (language) unique identifier.
         */
        'X-YB-Locale'?: Locale;
        /**
         * The `nextToken` returned by a previous call, which can be used to retrieve the next set of results.
         */
        'X-YB-NEXT-TOKEN'?: string;
    };
    path?: never;
    query?: never;
    url: '/trades';
};

export type GetTradesErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * IP address is banned
     */
    403: ProblemDetails;
    /**
     * Entity not found at server
     */
    404: ProblemDetails;
    /**
     * Precondition Failed
     */
    412: ProblemDetails;
    /**
     * Too many requests
     */
    429: ProblemDetails;
};

export type GetTradesError = GetTradesErrors[keyof GetTradesErrors];

export type GetTradesResponses = {
    /**
     * Successful operation
     */
    200: TradeCollection;
};

export type GetTradesResponse = GetTradesResponses[keyof GetTradesResponses];

export type GetChartsData = {
    body: ChartBarsPageRequest;
    headers: {
        /**
         * API token.
         */
        'X-YB-API-Key': string;
        /**
         * Locale (language) unique identifier.
         */
        'X-YB-Locale'?: Locale;
        /**
         * The `nextToken` returned by a previous call, which can be used to retrieve the next set of results.
         */
        'X-YB-NEXT-TOKEN'?: string;
    };
    path?: never;
    query?: never;
    url: '/charts';
};

export type GetChartsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * IP address is banned
     */
    403: ProblemDetails;
    /**
     * Entity not found at server
     */
    404: ProblemDetails;
    /**
     * Precondition Failed
     */
    412: ProblemDetails;
    /**
     * Too many requests
     */
    429: ProblemDetails;
};

export type GetChartsError = GetChartsErrors[keyof GetChartsErrors];

export type GetChartsResponses = {
    /**
     * Successful operation
     */
    200: Candles;
};

export type GetChartsResponse = GetChartsResponses[keyof GetChartsResponses];

export type GetDepthData = {
    body?: never;
    headers: {
        /**
         * API token.
         */
        'X-YB-API-Key': string;
        /**
         * Locale (language) unique identifier.
         */
        'X-YB-Locale'?: Locale;
    };
    path: {
        /**
         * Symbol name.
         */
        symbolName: string;
    };
    query?: {
        /**
         * Max number of price bands in response.
         */
        depth?: 5 | 10 | 25 | 100 | 250 | 1000;
    };
    url: '/depth/{symbolName}';
};

export type GetDepthErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * IP address is banned
     */
    403: ProblemDetails;
    /**
     * Entity not found at server
     */
    404: ProblemDetails;
    /**
     * Too many requests
     */
    429: ProblemDetails;
};

export type GetDepthError = GetDepthErrors[keyof GetDepthErrors];

export type GetDepthResponses = {
    /**
     * Successful operation
     */
    200: Book;
};

export type GetDepthResponse = GetDepthResponses[keyof GetDepthResponses];

export type GetTobData = {
    body?: never;
    headers: {
        /**
         * API token.
         */
        'X-YB-API-Key': string;
        /**
         * Locale (language) unique identifier.
         */
        'X-YB-Locale'?: Locale;
    };
    path: {
        /**
         * Symbol name.
         */
        symbolName: string;
    };
    query?: never;
    url: '/quote/{symbolName}';
};

export type GetTobErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * IP address is banned
     */
    403: ProblemDetails;
    /**
     * Entity not found at server
     */
    404: ProblemDetails;
    /**
     * Too many requests
     */
    429: ProblemDetails;
};

export type GetTobError = GetTobErrors[keyof GetTobErrors];

export type GetTobResponses = {
    /**
     * Successful operation
     */
    200: Quote;
};

export type GetTobResponse = GetTobResponses[keyof GetTobResponses];

export type GetTransfersHistoryData = {
    body: TransferRequestFilter;
    headers: {
        /**
         * API token.
         */
        'X-YB-API-Key': string;
        /**
         * Locale (language) unique identifier.
         */
        'X-YB-Locale'?: Locale;
        /**
         * The `nextToken` returned by a previous call, which can be used to retrieve the next set of results.
         */
        'X-YB-NEXT-TOKEN'?: string;
    };
    path?: never;
    query?: never;
    url: '/transfers';
};

export type GetTransfersHistoryErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * IP address is banned
     */
    403: ProblemDetails;
    /**
     * Entity not found at server
     */
    404: ProblemDetails;
    /**
     * Precondition Failed
     */
    412: ProblemDetails;
    /**
     * Too many requests
     */
    429: ProblemDetails;
};

export type GetTransfersHistoryError = GetTransfersHistoryErrors[keyof GetTransfersHistoryErrors];

export type GetTransfersHistoryResponses = {
    /**
     * Successful operation
     */
    200: TransferCollection;
};

export type GetTransfersHistoryResponse = GetTransfersHistoryResponses[keyof GetTransfersHistoryResponses];

export type GetConversionRateSingleData = {
    body: SingleConversionRateRequest;
    headers: {
        /**
         * API token.
         */
        'X-YB-API-Key': string;
        /**
         * Locale (language) unique identifier.
         */
        'X-YB-Locale'?: Locale;
    };
    path?: never;
    query?: never;
    url: '/conversion-rate/single';
};

export type GetConversionRateSingleErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * IP address is banned
     */
    403: ProblemDetails;
    /**
     * Entity not found at server
     */
    404: ProblemDetails;
    /**
     * Too many requests
     */
    429: ProblemDetails;
};

export type GetConversionRateSingleError = GetConversionRateSingleErrors[keyof GetConversionRateSingleErrors];

export type GetConversionRateSingleResponses = {
    /**
     * Successful operation
     */
    200: ConversionRate;
};

export type GetConversionRateSingleResponse = GetConversionRateSingleResponses[keyof GetConversionRateSingleResponses];

export type GetConversionRatesBatchData = {
    body: ConversionRatesBatchRequest;
    headers: {
        /**
         * API token.
         */
        'X-YB-API-Key': string;
        /**
         * Locale (language) unique identifier.
         */
        'X-YB-Locale'?: Locale;
    };
    path?: never;
    query?: never;
    url: '/conversion-rate/batch';
};

export type GetConversionRatesBatchErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * IP address is banned
     */
    403: ProblemDetails;
    /**
     * Entity not found at server
     */
    404: ProblemDetails;
    /**
     * Too many requests
     */
    429: ProblemDetails;
};

export type GetConversionRatesBatchError = GetConversionRatesBatchErrors[keyof GetConversionRatesBatchErrors];

export type GetConversionRatesBatchResponses = {
    /**
     * Successful operation
     */
    200: ConversionRatesBatchResponse;
};

export type GetConversionRatesBatchResponse = GetConversionRatesBatchResponses[keyof GetConversionRatesBatchResponses];

export type GetNowData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/now';
};

export type GetNowErrors = {
    /**
     * IP address is banned
     */
    403: unknown;
    /**
     * Too many requests
     */
    429: unknown;
};

export type GetNowResponses = {
    /**
     * Successful operation
     */
    200: Now;
};

export type GetNowResponse = GetNowResponses[keyof GetNowResponses];
